<%--
  Created by IntelliJ IDEA.
  User: ninhn
  Date: 1/12/2024
  Time: 2:25 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>Product List</title>
</head>
<body>
<h1>Product List</h1>
<table border="1">
    <tr>
        <th>Product ID</th>
        <th>Product Name</th>
        <th>Product Description</th>
        <th>Product Date</th>
        <th>Product Quantity</th>
        <th>Product Price</th>
        <th>Product Image</th>
        <th>Product Status</th>
        <th>Product Warranty</th>
        <th>Category ID</th>
        <th>Action</th>
    </tr>

    <!-- Include the content generated by the servlet -->
    <jsp:include page="/ProductServlet" />

</table>
</body>
</html>

